runtime: python39
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 2
  min_idle_instances: 1
  max_idle_instances: 1

entrypoint: gunicorn -b :$PORT server:app

env_variables:
  PYTHONUNBUFFERED: "True" 